language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
# command to install dependencies
install:
  - python setup.py install
  - pip install nose coverage coveralls
  
# command to run tests
script: coverage run `which nosetests`
after_success:
  - coveralls
